#+sbcl (shadow "SRC")

(defpackage #:clm 
  (:use #:cl)
  ;(:nicknames :clm)
  #+ccl(:import-from :walker walk-form)
  #+ccl(:import-from :ccl quit %get-cstring)
  #+sbcl (:import-from :sb-walker walk-form)
  #+sbcl (:import-from :sb-ext quit)
  #+sbcl (:shadow sb-alien:double)
  #+clisp (:import-from "WALKER" "WALK-FORM")
  #+excl (:import-from :clos walk-form)
  #+cmu (:import-from :walker walk-form)
  #+cmu (:import-from :alien def-alien-routine)
  #+sbcl (:import-from :sb-walker walk-form)
  #+sbcl (:import-from :sb-ext quit)
  #+sbcl (:shadow sb-alien:double)
  #+lispworks (:import-from :walker walk-form)
  #+(and excl cltl2) (:import-from :excl exit)
  #+(and clisp (not ansi-cl)) (:import-from :lisp bye shell)
  #+(and clisp ansi-cl) (:import-from :ext bye shell)
  #+cmu (:import-from "EXTENSIONS" "QUIT" "LOAD-FOREIGN"))

